version: "3.7"

services: 
  api:
    build: "./api"
    container_name: carford-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks: ['carford']
  
  web:
    build: "./web"
    container_name: carford-web
    restart: always
    ports:
      - "80:8501"
    depends_on:
      - api
    networks: ['carford']

networks: {carford: {}}